name: Build and Release leetcli (Cross-platform)

on:
  push:
    tags:
      - 'v*'  # Example: v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Install vcpkg and dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh || .\vcpkg\bootstrap-vcpkg.bat
          ./vcpkg/vcpkg install cpr nlohmann-json || .\vcpkg\vcpkg install cpr nlohmann-json

      - name: ⚙️ Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

      - name: 🛠️ Build leetcli
        run: cmake --build build --config Release --target install

      - name: 📦 Install leetcli
        run: cmake --install build --prefix install_dir

      - name: 🧹 Package executable
        run: |
          mkdir dist
          if [ "$RUNNER_OS" == "Windows" ]; then
            copy install_dir\\bin\\leetcli.exe dist\\leetcli.exe
            powershell Compress-Archive -Path dist\\leetcli.exe -DestinationPath leetcli-windows.zip
          elif [ "$RUNNER_OS" == "macOS" ]; then
            cp install_dir/bin/leetcli dist/leetcli-macos
            zip -j leetcli-macos.zip dist/leetcli-macos
          else
            cp install_dir/bin/leetcli dist/leetcli-linux
            zip -j leetcli-linux.zip dist/leetcli-linux
          fi
        shell: bash

      - name: 🚀 Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            leetcli-windows.zip
            leetcli-linux.zip
            leetcli-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
