name: Build and Release leetcli (Cross-platform)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install vcpkg and dependencies
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ./vcpkg/bootstrap-vcpkg.bat
            ./vcpkg/vcpkg.exe install cpr nlohmann-json
          else
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg install cpr nlohmann-json
          fi

      - name: Configure CMake
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build leetcli
        run: cmake --build build --config Release --target install

      - name: Install leetcli
        run: cmake --install build --prefix install_dir

      - name: Package leetcli (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          mkdir dist
          copy install_dir\bin\leetcli.exe dist\leetcli.exe
          copy install.bat dist\install.bat
          echo "leetcli - LeetCode CLI Tool" > dist\README.txt
          echo "" >> dist\README.txt
          echo "Installation:" >> dist\README.txt
          echo "1. Extract this ZIP file" >> dist\README.txt
          echo "2. Run install.bat as Administrator" >> dist\README.txt
          echo "3. Add the install\bin directory to your PATH" >> dist\README.txt
          echo "" >> dist\README.txt
          echo "Usage:" >> dist\README.txt
          echo "leetcli init" >> dist\README.txt
          Compress-Archive -Path dist\* -DestinationPath leetcli-windows.zip

      - name: Package leetcli (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          mkdir -p dist
          cp install_dir/bin/leetcli dist/leetcli
          cp install.sh dist/install.sh
          chmod +x dist/install.sh
          echo "leetcli - LeetCode CLI Tool" > dist/README.txt
          echo "" >> dist/README.txt
          echo "Installation:" >> dist/README.txt
          echo "1. Extract this ZIP file" >> dist/README.txt
          echo "2. Run: chmod +x install.sh && ./install.sh" >> dist/README.txt
          echo "3. Or manually copy leetcli to /usr/local/bin" >> dist/README.txt
          echo "" >> dist/README.txt
          echo "Usage:" >> dist/README.txt
          echo "leetcli init" >> dist/README.txt
          zip -j leetcli-macos.zip dist/*

      - name: Package leetcli (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          mkdir -p dist
          cp install_dir/bin/leetcli dist/leetcli
          cp install.sh dist/install.sh
          chmod +x dist/install.sh
          echo "leetcli - LeetCode CLI Tool" > dist/README.txt
          echo "" >> dist/README.txt
          echo "Installation:" >> dist/README.txt
          echo "1. Extract this ZIP file" >> dist/README.txt
          echo "2. Run: chmod +x install.sh && ./install.sh" >> dist/README.txt
          echo "3. Or manually copy leetcli to /usr/local/bin" >> dist/README.txt
          echo "" >> dist/README.txt
          echo "Usage:" >> dist/README.txt
          echo "leetcli init" >> dist/README.txt
          zip -j leetcli-linux.zip dist/*

      # Only macOS creates the release
      - name: Create GitHub Release (macOS only)
        if: runner.os == 'macOS'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} leetcli-macos.zip leetcli-linux.zip --title "Release ${{ github.ref_name }}" --notes "Auto-generated release from GitHub Actions

## Installation

### Windows
1. Download \`leetcli-windows.zip\`
2. Extract the ZIP file
3. Run \`install.bat\` as Administrator
4. Add the \`install\\bin\` directory to your PATH

### macOS/Linux
1. Download \`leetcli-macos.zip\` or \`leetcli-linux.zip\`
2. Extract the ZIP file
3. Run: \`chmod +x install.sh && ./install.sh\`
4. Or manually copy \`leetcli\` to \`/usr/local/bin\`

## Usage
\`\`\`bash
leetcli init
leetcli fetch daily
\`\`\`"

      # Others upload to the same release
      - name: Upload to GitHub Release
        if: runner.os != 'macOS'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} ${{ runner.os == 'Windows' && 'leetcli-windows.zip' || 'leetcli-linux.zip' }} --clobber
